package runtimeaction

import "time"

// Envelope is the normalized action presented to authorization.
// action_id is generated by the enforcement boundary, never trusted from an adapter.
type Envelope struct {
	Sequence     int              `json:"-"` // trusted receipt-chain sequence distinguishes repeated actions
	ActionID     string           `json:"action_id"`
	Platform     string           `json:"platform"`
	SessionID    string           `json:"session_id"`
	AgentID      string           `json:"agent_id"`
	TaskID       string           `json:"task_id"`
	IntentID     string           `json:"intent_id"`
	Tool         string           `json:"tool"`
	ToolCallID   string           `json:"tool_call_id,omitempty"`
	Operation    string           `json:"operation"`
	Effects      []string         `json:"effects"`
	Resources    []map[string]any `json:"resources,omitempty"`
	ParamsDigest string           `json:"params_digest"`
	OccurredAt   time.Time        `json:"occurred_at"`
}
