package admission

import (
	"fmt"
	"strings"

	"siq-agent-security/apps/agentshield/internal/display"
)

// renderCard produces the NVIDIA minimum skill card (dev-spec §3.6.6). Risk
// statements are derived from declared facts and findings so they are
// actionable rather than generic. The footer states that the card is neither a
// signature nor an approval.
//
// DEV15-C: original skill description is rendered only inside an untrusted
// metadata zone with terminal/Markdown escaping; it must not drive a TTY or
// break out of the card structure.
func renderCard(adm Admission, fm Frontmatter) string {
	get := func(k, def string) string {
		if v := strings.TrimSpace(fm.Fields[k]); v != "" {
			return v
		}
		return def
	}
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	w("# Skill Card\n\n")
	w("## Description\n\n")
	desc := get("description", "[unknown]")
	w("%s\n", display.ForMarkdownUntrusted(desc, 2000))
	w("Admission verdict: **%s** (engine %s, rulepack v%d, decided %s).\n\n", adm.Verdict, adm.Engine.Name, adm.Engine.RulepackVersion, adm.DecidedAt)
	w("## Owner\n\n%s\n\n", display.ForTerminal(get("author", get("owner", "[unknown]"))))
	w("## License/Terms of Use\n\n%s\n\n", display.ForTerminal(get("license", "[unknown]")))
	w("## Use Case\n\n%s\n\n", display.ForTerminal(get("compatibility", "[not declared in frontmatter]")))
	w("## Deployment Geography for Use\n\n[not declared]\n\n")

	w("### Requirements / Dependencies\n\n")
	cred := "No"
	for _, f := range adm.DeclaredFacts {
		if f.Domain == "credential" {
			cred = "Yes (declared: " + display.ForTerminal(f.Resource.Value) + ")"
			break
		}
	}
	w("Requires API Key or External Credential: %s\n\n", cred)
	w("Declared capabilities (state=declared, not yet granted):\n\n")
	if len(adm.DeclaredFacts) == 0 {
		w("- none\n")
	}
	for _, f := range adm.DeclaredFacts {
		w("- `%s` %s → %s `%s` (from %s)\n", f.Domain, f.Action, f.Resource.Type, display.ForTerminal(f.Resource.Value), f.SourceField)
	}
	w("\nDo not include secrets in prompts/logs/output; use least-privilege credentials; rotate keys as appropriate.\n\n")

	w("## Known Risks and Mitigations\n\n")
	risks := 0
	for _, f := range adm.Findings {
		if f.Disposition == dispInfo {
			continue
		}
		risks++
		line := ""
		if f.Location.Line != nil {
			line = fmt.Sprintf(":%d", *f.Location.Line)
		}
		path := display.ForTerminal(f.Location.Path)
		w("Risk: %s at `%s%s` (%s, %s/%.2f).\n\n", riskText(f), path, line, f.Category, f.Severity, f.Confidence)
		w("Mitigation: %s\n\n", mitigationText(f))
	}
	if risks == 0 {
		w("Risk: none detected by static analysis; runtime behaviour is still subject to grant and receipt controls.\n\n")
		w("Mitigation: run inside the granted allowlist; every tool call produces a signed receipt.\n\n")
	}

	w("## References\n\n- admission `%s` (content_hash `%s`)\n- rulepack v%d\n\n", adm.AdmissionID, adm.ContentHash, adm.Engine.RulepackVersion)
	w("## Skill Output\n\n[not declared]\n\n")
	w("## Skill Version\n\n%s (content_hash %s)\n\n", display.ForTerminal(ptrOr(adm.SkillVersion, "[unversioned]")), adm.ContentHash[:12])
	w("## Ethical Considerations\n\n")
	if adm.Verdict == "quarantine" {
		w("Quarantined: do not install until the flagged content is removed and re-admitted.\n\n")
	} else {
		w("Declared capabilities require human sign-off in grant before becoming effective; the model does not approve.\n\n")
	}
	w("---\n本卡由 agentshield 生成，不构成签名、批准或发布。/ Generated by agentshield; this card is not a signature, approval or release.\n")
	return b.String()
}

func riskText(f Finding) string {
	switch f.Category {
	case catHidden:
		return "hidden or invisible instructions that the user cannot see"
	case catInjection:
		return "prompt-injection phrasing that may hijack the agent's goal"
	case catDeception:
		return "instructions to deceive or withhold information from the user"
	case catExfil:
		if f.Disposition == dispQuarantine {
			return "credential access combined with an outbound channel (exfiltration path)"
		}
		return "reads credential material"
	case catIntegrity:
		return "integrity failure (" + f.RuleID + ")"
	case catDangerous:
		return "executes downloaded or dynamically constructed code"
	case catPersistence:
		return "installs persistence outside the skill directory"
	case catSupplyChain:
		return "ships a binary or native artifact that cannot be statically reviewed"
	case catCapability:
		return "requires capability " + f.RuleID
	}
	return f.RuleID
}

func mitigationText(f Finding) string {
	if f.Disposition == dispQuarantine {
		return "Quarantined. Remove the flagged content or obtain the skill from a verified source; re-run `agentshield admit`."
	}
	return "Recorded as a declared capability; it is denied until a human approves the corresponding grant, and every use is receipted."
}

func ptrOr(p *string, def string) string {
	if p == nil || *p == "" {
		return def
	}
	return *p
}
