#!/usr/bin/env python3
"""Validate native Hermes Agent conversations with a loopback synthetic model.

Uses the installed, unmodified Agent loop and plugin hooks. No provider credentials
or external model requests; temporary operator authority is held by the parent.
This is a conversation integration fixture, not a human approval or isolation claim.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import subprocess
import sys
import tempfile
import threading
import time
import traceback
from datetime import datetime, timezone
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parents[1]
loader = importlib.util.spec_from_file_location(
    "native_fixture", ROOT / "scripts/validate-intent-v2-hermes.py"
)
fixture = importlib.util.module_from_spec(loader)
loader.loader.exec_module(fixture)
require = fixture.require


def worker(spec_path):
    spec = json.loads(spec_path.read_text())
    root = Path(spec["fixture_root"]).resolve()
    allowed_connections = {
        (urlsplit(endpoint).hostname, urlsplit(endpoint).port)
        for endpoint in (spec["model_url"], os.environ["SIQ_AGENT_SECURITY_ENDPOINT"])
    }

    def guard(event, args):
        # A fixture boundary, not a production sandbox. Keep actual Hermes
        # transport and hook implementations intact; only bound their IO.
        if event == "socket.connect" and args[1] not in allowed_connections:
            raise PermissionError("fixture rejects non-fixture connection")
        if event == "socket.getaddrinfo" and args[0] not in ("127.0.0.1", "localhost"):
            raise PermissionError("fixture rejects external DNS")
        if event == "open" and isinstance(args[0], (str, bytes)):
            path = Path(os.fsdecode(args[0])).absolute()
            if not path.is_relative_to(root) and (
                path.name in (".env", ".op.env", "auth.json", "credentials.json")
                or path.is_relative_to(Path.home() / ".hermes")
            ):
                raise PermissionError("fixture rejects real configuration")

    sys.addaudithook(guard)
    sys.path.insert(0, spec["hermes_root"])
    from hermes_cli.plugins import discover_plugins
    from run_agent import AIAgent

    discover_plugins()
    agent = AIAgent(
        base_url=spec["model_url"],
        api_key="synthetic-fixture-key",
        provider="custom",
        api_mode="chat_completions",
        model="siq-synthetic-fixture",
        max_iterations=8,
        enabled_toolsets=["file"],
        quiet_mode=True,
        skip_context_files=True,
        skip_memory=True,
        skip_background_review=True,
        max_tokens=512,
        run_budget_seconds=45,
    )
    # Do not inject a session ID: bind the ID generated by the real runtime.
    Path(spec["ready_path"]).write_text(json.dumps({"session_id": agent.session_id}))
    deadline = time.monotonic() + 20
    while not Path(spec["go_path"]).exists():
        require(time.monotonic() < deadline, "parent binding handshake timed out")
        time.sleep(0.02)
    history = None
    for _ in range(spec["turns"]):
        result = agent.run_conversation(
            "Execute the supplied synthetic fixture sequence.",
            system_message="You are running a local synthetic integration fixture.",
            conversation_history=history,
        )
        require(
            result.get("final_response") == "fixture-conversation-complete",
            "Agent did not finish",
        )
        history = result["messages"]
    Path(spec["result_path"]).write_text(
        json.dumps({"session_id": agent.session_id, "completed": True})
    )


class ConversationHarness(fixture.Harness):
    def conversation(self, *, bound):
        label = "bound" if bound else "unbound"
        calls = (
            [
                self.read("allowed"),
                self.read("foreign-company", "company-b"),
                self.read("prefix-collision", "company-a-evil"),
                {
                    "id": "write-denied",
                    "tool": self.write_tool,
                    "params": {
                        "path": str(self.workspace / "company-a/must-not-exist.txt"),
                        "content": "synthetic forbidden write",
                    },
                },
                self.read("allowed-after-denials"),
            ]
            if bound
            else [self.read("missing-binding")]
        )
        requests, failures, metadata_requests = [], [], []
        # End one turn after two tools, then resume the same native session.
        steps = calls[:2] + [None] + calls[2:] + [None] if bound else calls + [None]

        class Model(BaseHTTPRequestHandler):
            def log_message(self, *_):
                pass

            def do_GET(self):
                metadata_requests.append(self.path)
                if self.path != "/v1/models":
                    self.send_error(404, "fixture endpoint unavailable")
                    return
                payload = json.dumps(
                    {
                        "object": "list",
                        "data": [
                            {
                                "id": "siq-synthetic-fixture",
                                "object": "model",
                                "created": 0,
                                "owned_by": "fixture",
                                "context_length": 131072,
                            }
                        ],
                    }
                ).encode()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(payload)))
                self.end_headers()
                self.wfile.write(payload)

            def do_POST(self):
                if self.path == "/api/show":
                    # Native local-server detection also probes Ollama.
                    metadata_requests.append(self.path)
                    self.send_error(404, "fixture is not an Ollama endpoint")
                    return
                try:
                    require(
                        self.path == "/v1/chat/completions",
                        "unexpected model route: " + self.path,
                    )
                    size = int(self.headers.get("Content-Length", "0"))
                    require(0 < size < 2_000_000, "invalid model request size")
                    body = json.loads(self.rfile.read(size))
                    tool_results = [m for m in body["messages"] if m["role"] == "tool"]
                    index = len(requests)
                    require(index < len(steps), "unexpected model retry")
                    completed = sum(step is not None for step in steps[:index])
                    require(len(tool_results) == completed, "Agent lost tool results")
                    user_turns = sum(m["role"] == "user" for m in body["messages"])
                    require(
                        user_turns == 1 + steps[:index].count(None),
                        "Agent lost turn history",
                    )
                    for call, result in zip(
                        calls[:completed], tool_results, strict=True
                    ):
                        require(
                            result["tool_call_id"] == call["id"],
                            "Agent lost tool call ID",
                        )
                        content = str(result["content"])
                        if call["id"].startswith("allowed"):
                            require(
                                "fixture-visible-company-a" in content,
                                "allowed read missing",
                            )
                        else:
                            require(
                                "fixture-visible-" not in content,
                                "denied content leaked to model",
                            )
                            require(
                                "siq-agent-security" in content,
                                "denial missing from Agent history",
                            )
                    requests.append(
                        {
                            "tool_result_count": len(tool_results),
                            "stream": bool(body.get("stream")),
                        }
                    )
                    message = {
                        "role": "assistant",
                        "content": "fixture-conversation-complete",
                    }
                    if steps[index] is not None:
                        call = steps[index]
                        message = {
                            "role": "assistant",
                            "content": None,
                            "tool_calls": [
                                {
                                    "id": call["id"],
                                    "type": "function",
                                    "function": {
                                        "name": call["tool"],
                                        "arguments": json.dumps(call["params"]),
                                    },
                                }
                            ],
                        }
                    payload = json.dumps(
                        {
                            "id": f"fixture-completion-{index}",
                            "object": "chat.completion",
                            "created": int(time.time()),
                            "model": "siq-synthetic-fixture",
                            "choices": [
                                {
                                    "index": 0,
                                    "message": message,
                                    "finish_reason": "tool_calls"
                                    if steps[index] is not None
                                    else "stop",
                                }
                            ],
                            "usage": {
                                "prompt_tokens": 100,
                                "completion_tokens": 20,
                                "total_tokens": 120,
                            },
                        }
                    ).encode()
                    content_type = "application/json"
                    if body.get("stream"):
                        completion = json.loads(payload)
                        delta = dict(message)
                        if "tool_calls" in delta:
                            delta["tool_calls"][0]["index"] = 0
                        chunks = []
                        for part, finish in (
                            (delta, None),
                            ({}, completion["choices"][0]["finish_reason"]),
                        ):
                            chunk = {
                                **completion,
                                "object": "chat.completion.chunk",
                                "choices": [
                                    {"index": 0, "delta": part, "finish_reason": finish}
                                ],
                            }
                            chunks.append("data: " + json.dumps(chunk) + "\n\n")
                        payload = ("".join(chunks) + "data: [DONE]\n\n").encode()
                        content_type = "text/event-stream"
                    self.send_response(200)
                    self.send_header("Content-Type", content_type)
                    self.send_header("Content-Length", str(len(payload)))
                    self.end_headers()
                    self.wfile.write(payload)
                except (RuntimeError, OSError, ValueError, KeyError, TypeError) as exc:
                    failures.append(type(exc).__name__ + ": " + str(exc))
                    self.send_error(400, "fixture assertion failed")

        server = ThreadingHTTPServer(("127.0.0.1", 0), Model)
        thread = threading.Thread(target=server.serve_forever, daemon=True)
        thread.start()
        ready, go, result, spec = [
            self.root / f"{label}-{name}.json"
            for name in ("ready", "go", "result", "spec")
        ]
        spec.write_text(
            json.dumps(
                {
                    "fixture_root": str(self.root),
                    "hermes_root": str(self.args.hermes_root),
                    "model_url": f"http://127.0.0.1:{server.server_port}/v1",
                    "ready_path": str(ready),
                    "go_path": str(go),
                    "result_path": str(result),
                    "turns": 2 if bound else 1,
                }
            )
        )
        env = {**self.env, "HERMES_MANAGED_DIR": str(self.root / "empty-managed")}
        proc = None
        try:
            with tempfile.TemporaryFile(mode="w+t") as log:
                proc = subprocess.Popen(
                    [
                        str(self.args.hermes_python),
                        str(Path(__file__).resolve()),
                        "--worker",
                        str(spec),
                    ],
                    cwd=self.workspace,
                    env=env,
                    stdout=log,
                    stderr=log,
                )
                deadline = time.monotonic() + 45
                while not ready.exists():
                    if proc.poll() is not None:
                        failure = spec.with_suffix(".failure.json")
                        detail = (
                            failure.read_text()
                            if failure.exists()
                            else "no worker diagnostic"
                        )
                        raise RuntimeError("Agent initialization failed: " + detail)
                    require(time.monotonic() < deadline, "Agent readiness timeout")
                    time.sleep(0.05)
                session = json.loads(ready.read_text())["session_id"]
                require(
                    session and session != fixture.SESSION,
                    "Agent session ID was not generated",
                )
                if bound:
                    self.api(
                        "/v1/intent-bindings",
                        {
                            "platform": "hermes",
                            "session_id": session,
                            "agent_id": fixture.AGENT,
                            "intent_id": "int-native-fixture",
                        },
                        expected=201,
                    )
                go.write_text("{}")
                require(
                    proc.wait(timeout=75) == 0,
                    "Agent conversation failed; model checks: " + repr(failures),
                )
                require(
                    json.loads(result.read_text())["session_id"] == session,
                    "session changed",
                )
        finally:
            if proc is not None and proc.poll() is None:
                proc.kill()
                proc.wait(timeout=10)
            server.shutdown()
            server.server_close()
            thread.join(timeout=5)
        require(
            not failures and len(requests) == len(steps),
            "incomplete model exchange",
        )
        records = self.receipts()
        parent_action = ""
        for seq, call in enumerate(calls, start=1):
            decision = self.assert_call(
                records,
                call["id"],
                "allow" if call["id"].startswith("allowed") else "deny",
                bound=bound,
            )
            require(
                decision["session_id"] == session,
                "native session detached from receipt",
            )
            require(decision["task_seq"] == seq, "task sequence reset across turns")
            require(
                decision.get("parent_action_id", "") == parent_action,
                "action parent changed across turns",
            )
            if decision["action"] == "allow":
                parent_action = decision["action_id"]
        require(
            not (self.workspace / "company-a/must-not-exist.txt").exists(),
            "denied write executed",
        )
        return {
            "bound": bound,
            "session_id": session,
            "model_requests": len(requests),
            "streaming_requests": sum(request["stream"] for request in requests),
            "tool_calls": len(calls),
            "turns": 2 if bound else 1,
            "metadata_requests": metadata_requests,
        }

    def run(self):
        self.build()
        self.start()
        self.setup_authority()
        conversations = [self.conversation(bound=True), self.conversation(bound=False)]
        require(
            conversations[0]["session_id"] != conversations[1]["session_id"],
            "sessions collided",
        )
        records = self.receipts()
        self.stop()
        verified = json.loads(self.command([str(self.binary), "verify"]))
        require(verified["verified"], "offline CLI verification failed")
        sources = [
            "run_agent.py",
            "agent/agent_init.py",
            "agent/conversation_loop.py",
            "agent/tool_executor.py",
        ]
        return {
            "schema": "intent-v2-hermes-conversation-validation/v1",
            "passed": True,
            "recorded_at": datetime.now(timezone.utc).isoformat(),
            "siq_commit": self.command(["git", "rev-parse", "HEAD"], cwd=ROOT).strip(),
            "siq_dirty": bool(
                self.command(["git", "status", "--porcelain"], cwd=ROOT).strip()
            ),
            **self.runtime_evidence(),
            "conversation_source_sha256": {
                p: hashlib.sha256((self.args.hermes_root / p).read_bytes()).hexdigest()
                for p in sources
            },
            "harness_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
            "shared_harness_sha256": hashlib.sha256(
                (ROOT / "scripts/validate-intent-v2-hermes.py").read_bytes()
            ).hexdigest(),
            "binary_sha256": hashlib.sha256(self.binary.read_bytes()).hexdigest(),
            "conversations": conversations,
            "receipt_count": len(records),
            "checks": self.checks
            + [
                "native_generated_session_binding",
                "native_model_response_tool_dispatch",
                "native_multi_turn_history_and_action_chain",
                "allowed_read_observed",
                "scope_and_write_denials_reach_model",
                "fresh_unbound_session_denied",
                "offline_receipt_chain_verified",
            ],
            "scope": "installed AIAgent.run_conversation with loopback synthetic chat completions and actual SIQ HTTP daemon",
            "limitations": [
                "synthetic model and operator, no real model quality or human approval proof",
                "no native Hermes hold approval journey",
                "no OpenClaw/CodeBuddy conversation or OS isolation claim",
            ],
        }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hermes-root", type=Path)
    parser.add_argument("--hermes-python", type=Path)
    parser.add_argument("--out", type=Path)
    parser.add_argument("--worker", type=Path, help=argparse.SUPPRESS)
    args = parser.parse_args()
    if args.worker:
        try:
            worker(args.worker)
        except Exception as exc:
            args.worker.with_suffix(".failure.json").write_text(
                json.dumps(
                    {
                        "type": type(exc).__name__,
                        "frames": [
                            {
                                "file": Path(f.filename).name,
                                "line": f.lineno,
                                "function": f.name,
                            }
                            for f in traceback.extract_tb(exc.__traceback__)
                        ],
                    }
                )
            )
            raise
        return
    require(
        args.hermes_root is not None and args.out is not None,
        "--hermes-root and --out required",
    )
    args.hermes_root = args.hermes_root.resolve()
    args.hermes_python = args.hermes_python or args.hermes_root / "venv/bin/python"
    with tempfile.TemporaryDirectory(prefix="siq-hermes-conversation-") as tmp:
        harness = ConversationHarness(Path(tmp), args)
        try:
            report = harness.run()
        finally:
            harness.stop()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n")
    print(
        json.dumps(
            {
                "passed": True,
                "conversations": report["conversations"],
                "receipt_count": report["receipt_count"],
            }
        )
    )


if __name__ == "__main__":
    try:
        main()
    except (
        RuntimeError,
        OSError,
        ValueError,
        KeyError,
        subprocess.SubprocessError,
    ) as exc:
        print(
            f"conversation validation failed: {type(exc).__name__}: {exc}",
            file=sys.stderr,
        )
        sys.exit(1)
