package receipt

import (
	"encoding/json"
	"os"
	"reflect"
	"sync"
	"testing"
	"time"
)

func TestHoldStatusContractSamples(t *testing.T) {
	load := func(name string, value any) {
		t.Helper()
		raw, err := os.ReadFile("../../testdata/contracts/" + name + ".sample.json")
		if err != nil {
			t.Fatal(err)
		}
		if err = json.Unmarshal(raw, value); err != nil {
			t.Fatal(err)
		}
	}
	var request HoldStatusRequest
	var expected HoldStatus
	load("hold-status-request.v1", &request)
	load("hold-status.v1", &expected)
	fx := newFixture(t, "block", deployedGrant(t, "openclaw", false), false)
	fx.eng.opts.Now = func() time.Time { return time.Date(2026, 9, 4, 7, 0, 0, 0, time.UTC) }
	d, err := fx.eng.Decide(Request{Platform: request.Platform, SessionID: request.SessionID, AgentID: request.AgentID, Tool: request.Tool, ToolCallID: request.ToolCallID, Params: request.Params})
	if err != nil {
		t.Fatal(err)
	}
	request.ActionID, request.DecisionReceiptID = d.Receipt.ActionID, d.Receipt.ReceiptID
	actual, err := fx.eng.ReadHoldStatus(request)
	if err != nil {
		t.Fatal(err)
	}
	// IDs are generated by the service; fixtures use explicit placeholders.
	actual.ActionID, actual.DecisionReceiptID = expected.ActionID, expected.DecisionReceiptID
	a, _ := json.Marshal(actual)
	b, _ := json.Marshal(expected)
	if !reflect.DeepEqual(a, b) {
		t.Fatalf("wire contract differs: %s versus %s", a, b)
	}
}

func statusRequest(req Request, d *Decision) HoldStatusRequest {
	return HoldStatusRequest{Platform: req.Platform, SessionID: req.SessionID, AgentID: req.AgentID, Tool: req.Tool, ToolCallID: req.ToolCallID, ActionID: d.Receipt.ActionID, DecisionReceiptID: d.Receipt.ReceiptID, Params: req.Params}
}

func TestHoldStatusIsReadOnlyBoundedAndRecovered(t *testing.T) {
	for _, approve := range []bool{false, true} {
		t.Run(map[bool]string{true: "approved", false: "denied"}[approve], func(t *testing.T) {
			fx := newFixture(t, "block", deployedGrant(t, "openclaw", false), false)
			r := req("openclaw", "exec", map[string]any{"command": "printf fixture"})
			d, err := fx.eng.Decide(r)
			if err != nil || d.Action != ActionHold {
				t.Fatal(d, err)
			}
			request := statusRequest(r, d)
			check := func(want string) *HoldStatus {
				t.Helper()
				value, err := fx.eng.ReadHoldStatus(request)
				if err != nil || value.Status != want || value.ActionID != request.ActionID || value.DecisionReceiptID != request.DecisionReceiptID {
					t.Fatalf("status: %+v %v, want %s", value, err, want)
				}
				return value
			}
			pending := check("pending")
			var wg sync.WaitGroup
			for i := 0; i < 12; i++ {
				wg.Add(1)
				go func() {
					defer wg.Done()
					value, err := fx.eng.ReadHoldStatus(request)
					if err != nil || value.Status != "pending" {
						t.Error(value, err)
					}
				}()
			}
			wg.Wait()
			before, err := fx.chain.Read()
			if err != nil || len(before) != 1 {
				t.Fatal("queries changed chain", err)
			}
			_, err = fx.eng.Observe(correlatedRequest(r, d), "forged")
			assertCorrelation(t, err, "observation_action_not_authorized")
			if _, err = fx.eng.ResolveHold(d.Receipt, approve, "admin"); err != nil {
				t.Fatal(err)
			}
			want := map[bool]string{true: "approved", false: "denied"}[approve]
			check(want)
			fx.eng, err = New(fx.eng.opts)
			if err != nil {
				t.Fatal(err)
			}
			if check(want).ExpiresAt != pending.ExpiresAt {
				t.Fatal("restart extended hold")
			}
			if approve {
				if _, err = fx.eng.Observe(correlatedRequest(r, d), "fixture"); err != nil {
					t.Fatal(err)
				}
				check("consumed")
				fx.eng, err = New(fx.eng.opts)
				if err != nil {
					t.Fatal(err)
				}
				check("consumed")
			}
			deadline, err := time.Parse(time.RFC3339Nano, pending.ExpiresAt)
			if err != nil {
				t.Fatal(err)
			}
			fx.eng.opts.Now = func() time.Time { return deadline }
			check("expired")
			all, err := fx.chain.Read()
			if err != nil {
				t.Fatal(err)
			}
			if len(all) != 2+map[bool]int{true: 1, false: 0}[approve] {
				t.Fatal("read appended receipts")
			}
			if err = Verify(all, fx.k.Public()); err != nil {
				t.Fatal(err)
			}
		})
	}
}

func TestHoldStatusRejectsIdentityAndAuthorityChanges(t *testing.T) {
	g := deployedGrant(t, "openclaw", false)
	fx := newFixture(t, "block", g, false)
	r := req("openclaw", "exec", map[string]any{"command": "printf fixture"})
	d, err := fx.eng.Decide(r)
	if err != nil {
		t.Fatal(err)
	}
	base := statusRequest(r, d)
	for _, edit := range []func(*HoldStatusRequest){
		func(r *HoldStatusRequest) { r.Platform = "other" }, func(r *HoldStatusRequest) { r.SessionID = "other" }, func(r *HoldStatusRequest) { r.AgentID = "other" }, func(r *HoldStatusRequest) { r.Tool = "other" }, func(r *HoldStatusRequest) { r.ToolCallID = "other" }, func(r *HoldStatusRequest) { r.ActionID = "other" }, func(r *HoldStatusRequest) { r.DecisionReceiptID = "other" }, func(r *HoldStatusRequest) { r.Params = map[string]any{"command": "changed"} }, func(r *HoldStatusRequest) { r.ActionID = "" }, func(r *HoldStatusRequest) { r.Params = nil },
	} {
		changed := base
		edit(&changed)
		if _, err := fx.eng.ReadHoldStatus(changed); err == nil {
			t.Fatal("accepted changed identity")
		}
	}
	if _, err = fx.eng.ResolveHold(d.Receipt, true, "admin"); err != nil {
		t.Fatal(err)
	}
	g.Status = "revoked"
	status, err := fx.eng.ReadHoldStatus(base)
	if err != nil || status.Status != "denied" || status.ReasonCode != "hold_authority_changed" {
		t.Fatal(status, err)
	}
}
